### ISSUE TITLE
Will it works with application with admin rights needed ?

### ISSUE THREAD

**Issue by mooms06** [mbooga/owclauncher#1]
Hi, see this issue to understand:
https://github.com/darktrojan/openwith/issues/163

**Comment by mbooga** [comment]
Sorry for the late reply,
Just tested on Windows 10 64 v1803
Running apps requiring admin rights through owclauncher seems to function correctly

Let me know if you have specific non working examples.
also, I'm open to pull requests

**Comment by mooms06** [comment]
Indeed, just tested and it's working, thank you !
